### ISSUE TITLE
关于发布到crates的讨论

### ISSUE THREAD

**Issue by ChengYueJia** [apache/dubbo-rust#17]
1. 确认一下，crates.io上的dubbo的包是否跟本项目有关。
   如果无关的话，建议dubbo-rust里面的dubbo子package改名为dubbo-core
   [see more about crates.io/rust](https://crates.io/crates/dubbo)
2. 因为crates.io 上的包名遵循先到先得的方式，建议在crates.io上面尽快申请dubbo相关的包名。
   [https://doc.rust-lang.org/stable/cargo/reference/publishing.html](https://doc.rust-lang.org/stable/cargo/reference/publishing.html)

**Comment by Ticsmtc** [comment]
感谢提醒
1. crates.io 上的 dubbo 据我所知与本项目无关
2. 包名按照 rust 习惯规则进行重新命名，例如 core -> dubbo-core 将会在下一次主线合并更改。

**Comment by ChengYueJia** [comment]
因为没有跟诸位讨论，
 #16   中所以我提的这个mr没有涉及现在的dubbo package命名的改动。。
