### ISSUE TITLE
2022-04-25 社区第一次会议

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-rust#4]
## 会议纪要
参会人员：刘军、郭炜斌、过迷雾、月半酱

会议结论：
* 讨论了 dubbo rust 项目的第一阶段总体目标：先实现 rpc 通信协议，再迭代服务治理如服务发现等能力
* Apache 项目注意事项：以来代码一定兼容 Apache License，引用开源代码一定提前说明并注明出处
* 前期先由刘军负责协调项目工作，包括在大家成为 Apache Committer 前负责合并代码

任务项：
* 刘军 给出 Dubbo 总体架构，并尝试对任务项进行分解
* 过迷雾 搭建项目基本结构
* 调研 Tonic ，尝试参考设计出 dubbo triple 协议实现的基本架构与流程、包括框架选型等

**Comment by artorias1024** [comment]
确定围绕tokio生态吗？

**Comment by Johankoi** [comment]
> 确定围绕tokio生态吗？

是的，tokio几近成为标准

**Comment by dongzl** [comment]
大佬们好，入门级 rust 选手可以参与咱们这个项目吗？^_^

**Comment by dongzl** [comment]
https://tokio.rs/

https://github.com/tokio-rs/tokio

**Comment by iamazy** [comment]
dubbo小白可以旁听会议吗
