### ISSUE TITLE
Rft: refactor config module and Dubbo init

### ISSUE THREAD

**Issue by Rianico** [apache/dubbo-rust#65]
## The Goal
This issue aims at fixing the problem about config initialization and make the `Dubbo::init` "more rust".

## Description
Hello everyone, I have found some little problems about config module, and some code style in `Dubbo::init`:

1. In `config` module, the `config::GLOBAL_ROOT_CONFIG` use `lazy_static!` to create a `RwLock`, but the `RootConfig` may be initialized multiple time due to get the read lock incorrectly:  
```rust
if GLOBAL_ROOT_CONFIG.read().unwrap().as_ref().is_none() { // the read lock has already be dropped
    ...
    // may be write multiple times
    *GLOBAL_ROOT_CONFIG.write().unwrap() = Some(c);
}
```
Regardless of the complex `RwLock`, maybe we can use `once_cell` instead of `lazy_static`, which has merged into Rust Nightly.
2. `Dubbo::init` exists many condition branch like `if xxx.is_some()`, but use pattern match (e.g. `if let Some(v)`) is more general in Rust (refer to #19 and [P.CTF.02 优先使用模式匹配而非判断后再取值](https://rust-coding-guidelines.github.io/rust-coding-guidelines-zh/safe-guides/coding_practice/control-flow/P.CTF.02.html#pctf02-%E4%BC%98%E5%85%88%E4%BD%BF%E7%94%A8%E6%A8%A1%E5%BC%8F%E5%8C%B9%E9%85%8D%E8%80%8C%E9%9D%9E%E5%88%A4%E6%96%AD%E5%90%8E%E5%86%8D%E5%8F%96%E5%80%BC)).

**Comment by yang20150702** [comment]
Good work. Your code style is "more rust".
